# Site settings
title: [Your Name] Speaker Portfolio
email: your-email@example.com
description: >-
  My public speaking portfolio, technical papers, and blog posts.
baseurl: "/speaking-and-writing" # Replace with your repo name
url: "https://your-username.github.io"

# Theme Configuration
remote_theme: daattali/beautiful-jekyll
